[package]
name = "frontend"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description.workspace = true
license-file.workspace = true
readme.workspace = true

[dependencies]
leptos = { version = "0.6", features = ["csr"] }
leptos_meta = { version = "0.6", features = ["csr"] }
leptos_router = { version = "0.6", features = ["csr"] }
shared = { path = "../shared" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }
# Para WebSockets en Wasm
futures = "0.3"
gloo-net = { version = "0.3", features = ["websocket"] }
tokio = { version = "1", features = ["sync", "macros"] }
console_error_panic_hook = "0.1"

[lints]
workspace = true
