[workspace]
members = [
    "backend",
    "shared",
    "frontend"
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.7.0"
authors = ["oscar-bio-dev"]
repository = "https://github.com/oscar-bio-dev/oscar-bio-dev"
keywords = ["iot", "telemetry", "rust"]
categories = ["science", "embedded"]
description = "Industrial grade telemetry hub for environmental monitoring"
license-file = "LICENSE.txt"
readme = "README.md"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"

[workspace.lints.clippy]
cargo_common_metadata = "allow"
