services:
  db:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: oscar_bio_dev_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oscar_bio_dev
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/home/postgres/pgdata/data
    restart: always

volumes:
  timescaledb_data:
