[package]
name = "backend"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description.workspace = true
license-file.workspace = true
readme.workspace = true

[dependencies]
shared = { path = "../shared" }
# El servidor web (router)
axum = { version = "0.7", features = ["ws", "macros"] }
# El runtime asíncrono
tokio = { version = "1.36", features = ["full"] }
# Para servir archivos estáticos (CSS, imágenes)
tower-http = { version = "0.5", features = ["fs", "cors", "trace", "timeout", "limit"] }
chrono = { version = "0.4.45", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
serde_json = "1.0.151"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
utoipa = { version = "4", features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { version = "7", features = ["axum"] }
tower = { version = "0.5", features = ["timeout", "limit"] }
tower_governor = "0.4.2"
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "postgres", "chrono", "uuid"] }
validator = { version = "0.19", features = ["derive"] }
dotenvy = "0.15"
prost = "0.13"
bytes = "1.5"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
futures-util = "0.3"
lru = "0.18.3"
google-cloud-pubsub = "1.4.0"
base64 = "0.23.1"

[dev-dependencies]
proptest = "1.4"

[lints]
workspace = true
