// Copyright (c) 2026 Oscar Mora / SetaeSense. All rights reserved.
// Proprietary and confidential.

use crate::api::digital_twin::validate_api_key;
use crate::domain::state::AppState;
use axum::{
    extract::State,
    http::{HeaderMap, StatusCode},
    response::IntoResponse,
    Json,
};
use serde::{Deserialize, Serialize};
use std::env;

/// Request DTO para el Chatbot.
#[derive(Deserialize, utoipa::ToSchema)]
pub struct ChatRequest {
    /// Consulta del usuario
    pub message: String,
}

/// Response DTO para el Chatbot.
#[derive(Serialize, utoipa::ToSchema)]
pub struct ChatResponse {
    /// Respuesta de la IA
    pub reply: String,
}

#[derive(Serialize)]
struct GeminiRequest {
    contents: Vec<GeminiContent>,
}

#[derive(Serialize)]
struct GeminiContent {
    parts: Vec<GeminiPart>,
}

#[derive(Serialize)]
struct GeminiPart {
    text: String,
}

#[derive(Deserialize)]
struct GeminiResponse {
    candidates: Option<Vec<GeminiCandidate>>,
}

#[derive(Deserialize)]
struct GeminiCandidate {
    content: GeminiContentResp,
}

#[derive(Deserialize)]
struct GeminiContentResp {
    parts: Vec<GeminiPartResp>,
}

#[derive(Deserialize)]
struct GeminiPartResp {
    text: String,
}

/// Endpoint para consultar a la IA sobre el estado del Gemelo Digital.
#[utoipa::path(
    post,
    path = "/api/chat",
    request_body = ChatRequest,
    security(
        ("bearerAuth" = [])
    ),
    responses(
        (status = 200, description = "Respuesta de la IA", body = ChatResponse),
        (status = 401, description = "No autorizado - API Key faltante o inválida"),
        (status = 500, description = "Error interno al comunicarse con Gemini")
    )
)]
#[allow(clippy::unused_async)]
pub async fn chat_with_twin(
    headers: HeaderMap,
    State(state): State<AppState>,
    Json(payload): Json<ChatRequest>,
) -> Result<impl IntoResponse, (StatusCode, String)> {
    // 1. Autenticación
    validate_api_key(&headers)?;

    // 2. Extraer estado del Gemelo Digital
    let twin_data = {
        let twin = state.digital_twin.read().await;
        serde_json::to_string_pretty(&*twin).unwrap_or_default()
    };

    // 3. Construir el System Prompt para Gemini
    let system_prompt = format!(
        "You are the Cognitive Digital Twin AI for an industrial ecological monitoring system (oscar-bio-dev).\n\
        The current real-time telemetry from all active hardware nodes is provided below in JSON format:\n\
        {twin_data}\n\
        \n\
        Rules:\n\
        - Answer the user's question concisely based ONLY on this telemetry data.\n\
        - If they ask for something not present in the data, state clearly that you don't have that information.\n\
        - Be professional, but maintain a slightly cyberpunk/hacker tone suitable for an Agent Terminal UI."
    );

    let full_prompt = format!("{system_prompt}\n\nUser Question: {}", payload.message);

    // 4. Llamar a la API de Gemini
    let gemini_key = env::var("GEMINI_API_KEY").map_err(|_| {
        tracing::error!("GEMINI_API_KEY no configurada en el servidor");
        (StatusCode::INTERNAL_SERVER_ERROR, "AI not configured on server".to_string())
    })?;

    let url = format!(
        "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={gemini_key}"
    );

    let req_body = GeminiRequest {
        contents: vec![GeminiContent { parts: vec![GeminiPart { text: full_prompt }] }],
    };

    let client = reqwest::Client::new();
    let res = client.post(&url).json(&req_body).send().await.map_err(|e| {
        tracing::error!("Fallo en request a Gemini: {}", e);
        (StatusCode::INTERNAL_SERVER_ERROR, "AI request failed".to_string())
    })?;

    if !res.status().is_success() {
        tracing::error!("Gemini API error: {}", res.status());
        return Err((StatusCode::INTERNAL_SERVER_ERROR, "AI API returned an error".to_string()));
    }

    let gemini_resp: GeminiResponse = res.json().await.map_err(|e| {
        tracing::error!("Error parseando Gemini response: {}", e);
        (StatusCode::INTERNAL_SERVER_ERROR, "AI Response parse error".to_string())
    })?;

    // Extraer el texto de la respuesta
    let reply_text = gemini_resp
        .candidates
        .and_then(|mut c| c.pop())
        .and_then(|mut c| c.content.parts.pop())
        .map_or_else(|| "No response generated by the AI.".to_string(), |p| p.text);

    Ok(Json(ChatResponse { reply: reply_text }))
}
